config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  authenticate :user do
    mount Sidekiq::Web => "/sidekiq"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#welcome"
  get "home", to: "pages#home", as: "home"
  get "chat/:id", to: "chat#show", as: "chat"
  post "send_message", to: "chat#send_message", as: "send_message"
  post "send_message_to_chat/:id", to: "chat#send_message_to_chat", as: "send_message_to_chat"
  delete "delete_chat/:id", to: "chat#delete_chat", as: "delete_chat"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  validates :content, presence: true
  enum message_type: [ :question, :response ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chats, dependent: :destroy
  has_many :messages, through: :chats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  private

  def after_sign_in_path_for(resource)
     "/home"
  end
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  before_action :authenticate_user!, only: [ :show, :delete_chat ]

  def show
    @findChat = Chat.find(params[:id])
    @messages = @findChat.messages
  end

  def send_message
    @new_chat = current_user.chats.create!(title: params[:message][0, 20])
    @message = @new_chat.messages.create!(content: params[:message], message_type: :question)
    ResponseJob.perform_async(@message.content, @new_chat.id)
    redirect_to chat_path(@new_chat)
  end

  def send_message_to_chat
    chat = current_user.chats.find(params[:id])
    @message = chat.messages.create!(content: params[:message], message_type: :question)
    @sentmessage = params[:message]

    ResponseJob.perform_async(@sentmessage, chat.id)

    respond_to do |format|
      format.turbo_stream
    end
  end



  def delete_chat
   @chat = current_user.chats.find(params[:id])
   puts @chat
    if @chat.destroy
      respond_to do |format|
        format.turbo_stream {
          render turbo_stream: turbo_stream.remove("chat#{@chat.id}")
         }
      end
    else
      Rails.logger.debug @chat.errors.full_messages.join(", ")
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [ :home ]
  def welcome
  end
  def home
    @chats = current_user.chats
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [ :create ]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :username, :email, :password, :password_confirmation ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chat/send_message.html.erb
<p>
  <%= @message.content %>
</p>

app/views/chat/send_message_to_chat.turbo_stream.erb
<%= turbo_stream.append "message-list" do %>
  <%= render partial: "shared/message", locals: { message: @message } %>
<% end %>

app/views/chat/show.html.erb
<div data-controller="add-message" id="chatag<%=@findChat.id%>" data-body-target="chat">
  <div class="py-[80px] ">
    <%= turbo_frame_tag "message-list", data: { "add-message-target" => "messages" } do %>
      <%= render partial: "shared/message", collection: @messages, as: :message %>
    <% end %>
  </div>

  <div class="fixed bottom-0 py-2 w-[80%] bg-gray-300 flex justify-center left-[20%]">
    <%= form_with url: send_message_to_chat_path(@findChat), method: :post, local: false, class: "w-8/12 p-4 bg-gray-600 flex items-center rounded-full justify-center", data: { "add-message-target" => "form" } do |form| %>
      <%= form.text_area :message, placeholder: "Message ASK ME AI", 
          class: "bg-transparent resize-none h-[45px] text-wrap flex items-center border-none max-h-[350px] w-11/12 mr-4 text-gray-100", 
          data: { "add-message-target" => "chatinput" } %>
      <button type="submit" class="bg-gray-500 rounded-full text-lg h-[38px] w-[38px] text-gray-200" data-action="click->add-message#submitInput">
        <i class="fa-solid fa-arrow-up"></i>
      </button>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Chat Bot" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-300" data-controller="body">
    <%= turbo_stream_from "message-list" %>
    <% if user_signed_in? %>
      <div class="w-[20%] min-h-screen p-4 px-2 fixed mt-[75px] shadow-md bg-gray-400 shadow-gray-300">
        <div class="flex justify-between items-center mb-5">
          <h3 class="capitalize text-xl font-bold">Chat History</h3>
          <%= link_to home_path, class: "text-xl" do %>
            <%= icon('fa-solid', 'plus')%>
          <%end%>
        </div>
        <%= render "shared/chats", chats: current_user.chats %>
      </div>

      <nav class="bg-gray-400 fixed top-0 w-full h-[70px] p-5">
        <%= link_to "logout", destroy_user_session_path, data: {turbo_method: :delete} %>
      </nav>
    <% end %>
    <main class="w-[80%] bg-gray-300 ml-auto px-10">
      <%= yield %>
    </main>
  </body>
</html>
 

app/views/pages/home.html.erb
<section id="main-screen" class= "min-h-screen flex flex-col justify-center items-center">
   <h3 class="text-3xl mb-10 font-bold">What can I help you with?</h3>
   <div class="w-1/2 auto flex justify-center">
     <%= form_with(url: send_message_path, method: :post, class: "w-full py-[5px] bg-gray-500 px-5 border-none flex items-center justify-between rounded-3xl") do |form| %>
      <%= form.text_field :message, placeholder: "Message ASK ME AI", 
        class: "w-10/12 bg-transparent text-gray-100 outline-none resize-none border-none h-[50px] text-wrap max-h-[350px] mr-4"%>
      <button type="submit" class="bg-gray-400 rounded-full text-lg h-[38px] w-[38px] text-gray-200" data-action="click->add-message#submitInput">
        <i class="fa-solid fa-arrow-up"></i>
      </button>
    <% end %>
   </div>
</section>

app/views/pages/welcome.html.erb
<%if user_signed_in?%>
<div class="flex justify-center h-screen w-full items-center flex-col">
  <p class=" text-3xl mb-5 font-bold">Welcome to ASK ME chat-AI </p> 
  <div class="my-5">
    <p>You are <%= current_user.username %></p>
  </div>
</div>
    <%else%>
    <div class="flex min-h-full absolute left-0 justify-center h-screen w-full items-center flex-col">
      <p class=" text-3xl mb-5 font-bold">Welcome to ASK ME chat-AI </p> 
      <div class="my-5">
        <%= link_to "sign In", new_user_session_path, class: " border-[1px] text-xl border-blue-400 rounded-md mr-2 p-3 px-8 bg-blue-400 capitalize text-white" %> 
        <%= link_to "sign Up", new_user_registration_path, class: "border-[1px] text-xl border-blue-400 rounded-md mr-2 p-3 px-8 hover:bg-blue-400 hover:text-white capitalize" %> 
      </div>
   </div>
<%end%>

app/views/shared/_chats.html.erb
<div id="chat-wrapper">
 <% if chats.empty? %>
  <p>No chat History yet</p>
 <%else%>
    <%= render partial: "shared/eachchat", collection:chats, as: :chat %>
  <%end%>
</div>

app/views/shared/_eachchat.html.erb
<div class="p-4 bg-gray-300 my-2 rounded-md flex justify-between items-center" id="chat<%= chat.id %>" data-body-target="chat">
  <% truncated_title = chat.title.length > 17 ? "#{chat.title}..." : chat.title %>
  <%= link_to truncated_title, chat_path(chat), class: "w-10/12" %>
  
  <%= link_to delete_chat_path(chat) ,  data: {turbo_method: :delete, action: "click->body#delete_chat", body_id_param: chat.id }, class: "text-red-400" do %>
    <%= icon('fa-solid', 'trash') %>
  <% end %>
</div>

app/views/shared/_message.html.erb
<div id="<%= dom_id(message) %>" class="<%= message.message_type == 'question' ? 'bg-gray-500 ml-auto' : 'bg-gray-600 mr-auto' %> w-fit max-w-[45%] text-gray-100 p-4 rounded-lg my-3">
  <p><%= message.content %></p>
  <span class="text-xs w-full text-right block mt-2"><%= message.created_at.strftime("%H:%M %p") %></span>
</div>

app/views/shared/_test.html.erb
<p><%= message %></p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>